package May;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
Example 2:

Input: s = "", t = "y"
Output: "y"

 */
public class May12 {
    public static void main(String[] args) {
        System.out.println(findTheDifference("abcde","abxcde"));
        System.out.println(findTheDifference2("a", "aa"));
        System.out.println(findTheDifference3("ymbgaraibkfmvocpizdydugvalagaivdbfsfbepeyccqfepzvtpyxtbadkhmwmoswrcxnargtlswqemafandgkmydtimuzvjwxvlfwlhvkrgcsithaqlcvrihrwqkpjdhgfgreqoxzfvhjzojhghfwbvpfzectwwhexthbsndovxejsntmjihchaotbgcysfdaojkjldprwyrnischrgmtvjcorypvopfmegizfkvudubnejzfqffvgdoxohuinkyygbdzmshvyqyhsozwvlhevfepdvafgkqpkmcsikfyxczcovrmwqxxbnhfzcjjcpgzjjfateajnnvlbwhyppdleahgaypxidkpwmfqwqyofwdqgxhjaxvyrzupfwesmxbjszolgwqvfiozofncbohduqgiswuiyddmwlwubetyaummenkdfptjczxemryuotrrymrfdxtrebpbjtpnuhsbnovhectpjhfhahbqrfbyxggobsweefcwxpqsspyssrmdhuelkkvyjxswjwofngpwfxvknkjviiavorwyfzlnktmfwxkvwkrwdcxjfzikdyswsuxegmhtnxjraqrdchaauazfhtklxsksbhwgjphgbasfnlwqwukprgvihntsyymdrfovaszjywuqygpvjtvlsvvqbvzsmgweiayhlubnbsitvfxawhfmfiatxvqrcwjshvovxknnxnyyfexqycrlyksderlqarqhkxyaqwlwoqcribumrqjtelhwdvaiysgjlvksrfvjlcaiwrirtkkxbwgicyhvakxgdjwnwmubkiazdjkfmotglclqndqjxethoutvjchjbkoasnnfbgrnycucfpeovruguzumgmgddqwjgdvaujhyqsqtoexmnfuluaqbxoofvotvfoiexbnprrxptchmlctzgqtkivsilwgwgvpidpvasurraqfkcmxhdapjrlrnkbklwkrvoaziznlpor",
                "qhxepbshlrhoecdaodgpousbzfcqjxulatciapuftffahhlmxbufgjuxstfjvljybfxnenlacmjqoymvamphpxnolwijwcecgwbcjhgdybfffwoygikvoecdggplfohemfypxfsvdrseyhmvkoovxhdvoavsqqbrsqrkqhbtmgwaurgisloqjixfwfvwtszcxwktkwesaxsmhsvlitegrlzkvfqoiiwxbzskzoewbkxtphapavbyvhzvgrrfriddnsrftfowhdanvhjvurhljmpxvpddxmzfgwwpkjrfgqptrmumoemhfpojnxzwlrxkcafvbhlwrapubhveattfifsmiounhqusvhywnxhwrgamgnesxmzliyzisqrwvkiyderyotxhwspqrrkeczjysfujvovsfcfouykcqyjoobfdgnlswfzjmyucaxuaslzwfnetekymrwbvponiaojdqnbmboldvvitamntwnyaeppjaohwkrisrlrgwcjqqgxeqerjrbapfzurcwxhcwzugcgnirkkrxdthtbmdqgvqxilllrsbwjhwqszrjtzyetwubdrlyakzxcveufvhqugyawvkivwonvmrgnchkzdysngqdibhkyboyftxcvvjoggecjsajbuqkjjxfvynrjsnvtfvgpgveycxidhhfauvjovmnbqgoxsafknluyimkczykwdgvqwlvvgdmufxdypwnajkncoynqticfetcdafvtqszuwfmrdggifokwmkgzuxnhncmnsstffqpqbplypapctctfhqpihavligbrutxmmygiyaklqtakdidvnvrjfteazeqmbgklrgrorudayokxptswwkcircwuhcavhdparjfkjypkyxhbgwxbkvpvrtzjaetahmxevmkhdfyidhrdeejapfbafwmdqjqszwnwzgclitdhlnkaiyldwkwwzvhyorgbysyjbxsspnjdewjxbhpsvj"));

    }


    //this solution will work if there are no duplicate characters, if s="a" and t="aa", this won't work.
    static char findTheDifference(String s, String t){
        char[] sArray = new char[s.length()];
        char[] tArray = new char[t.length()];

        int j=0;
        j=0;
        for (int i = 0; i <t.length() ; i++) {
           tArray[i] = t.charAt(i);
        }
        for (int i = 0; i <tArray.length ; i++) {
            if(!s.contains(Character.toString(tArray[i]))){
                return tArray[i];
            }
        }
        return '0';
    }
    static char findTheDifference2(String s, String t){
        Map<Character,Integer> map = new HashMap<>();
        for (int i = 0; i <t.length() ; i++) {
            if(!map.containsKey(t.charAt(i))){
                map.put(t.charAt(i),1);
            }else{
                int newCount = map.get(t.charAt(i)) + 1;
                map.put(t.charAt(i), newCount);
            }
        }
        for (int i = 0; i <s.length() ; i++) {
            if(map.get(s.charAt(i)) == 1){
                map.remove(s.charAt(i));
            }else{
                map.replace(s.charAt(i),1);
            }
        }
        for(Map.Entry<Character, Integer> entry : map.entrySet()){
            return entry.getKey();
        }
        return 0; //not found
    }

    private static int findStringSum(String s) {
        int sum = 0;
        // find sum of ASCII values of characters in the string
        for(int i=0;i<s.length();i++)
            sum += (int) s.charAt(i);
        return sum;
    }

    public static char findTheDifference3(String s, String t) {
        // subtract s from t to get ASCII value of character added to t
        return (char) (findStringSum(t) - findStringSum(s));
    }

}
